<?xml version="1.0"?>

<robot name="two_wheel_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="tag_material" value="$(arg tag_index)"/>
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass1" value="0.03" /> <!-- arbitrary value for box mass -->
  <xacro:property name="mass2" value="0.002" /> <!-- arbitrary value for wheel mass -->
  <xacro:property name="mass3" value="0.002" /> <!-- arbitrary value for wheel mass -->
  <xacro:property name="width" value="0.1" /> <!-- box width -->
  <xacro:property name="radius" value="0.059" /> <!-- wheel radius -->
  <xacro:property name="length" value="0.01" />  <!-- wheel length -->
  <xacro:property name="radius3" value="0.059" /> <!-- wheel radius -->
  <xacro:property name="length3" value="0.08" />  <!-- wheel length -->
  <xacro:arg name="ns" default=""/>
  
  <gazebo>
    <plugin filename="libgazebo_ros_diff_drive.so" name="differential_drive_controller">
      <legacyMode>false</legacyMode>
      <alwaysOn>true</alwaysOn>
      <updateRate>20</updateRate>
      <leftJoint>left_motor</leftJoint>
      <rightJoint>right_motor</rightJoint>
      <wheelSeparation>${length + width}</wheelSeparation>
      <wheelDiameter>${radius * 2}</wheelDiameter>
      <torque>20</torque>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_link</robotBaseFrame>
      <!-- <publishOdomTF>false</publishOdomTF> -->
      <publishWheelJointState>true</publishWheelJointState>
    </plugin>
  </gazebo>

  <gazebo reference="base_link">
    <material value="${tag_material}" />
  </gazebo>

  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>
  <material name="blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>
  <material name="green">
    <color rgba="0.0 0.8 0.0 1.0"/>
  </material>
  <material name="grey">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>
  <material name="orange">
    <color rgba="1.0 0.423529411765 0.0392156862745 1.0"/>
  </material>
  <material name="brown">
    <color rgba="0.870588235294 0.811764705882 0.764705882353 1.0"/>
  </material>
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>
  <material name="white">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>

<!-- inertial property cannot exist in root link -->
<link name="base_link">
  <visual>
    <origin xyz="0 0 ${width/2}" />
    <geometry>
      <box size="${width} ${width} ${width}"/>
      <!-- <mesh filename="package://two_wheel_robot_description/meshes/twowheel_body.dae"/> -->
    </geometry>
  </visual>
</link>

<link name="body_link">
  <inertial>
    <mass value="${mass1}" />
    <origin xyz="0 0 ${width/2}" />
    <inertia ixx="${mass1 / 12.0 * (width*width + width*width)}" ixy="0.0" ixz="0.0"
      iyy="${mass1 / 12.0 * (width*width + width*width)}" iyz="0.0"
      izz="${mass1 / 12.0 * (width*width + width*width)}" />
  </inertial>

  <collision>
    <origin xyz="0 0 ${width/2}" />
    <geometry>
      <box size="${width} ${width} ${width}"/>
      <!-- <mesh filename="package://two_wheel_robot_description/meshes/twowheel_body.dae"/> -->
    </geometry>
  </collision>
</link>

<gazebo reference="body_link">
  <!-- tag name has to be mu1, though in gazebo they are mu and mu2 -->
  <!-- <mu1>0.1</mu1>
  <mu2>0.1</mu2> -->
</gazebo>


<!-- support the robot body from swing front and back -->
<link name="front_sphere">
  <inertial>
    <mass value="0.0000001" />
    <origin xyz="0 0 0" />
    <inertia ixx="0.00000000001" ixy="0.0" ixz="0.0"
      iyy="0.00000000001" iyz="0.0"
      izz="0.00000000001" />
  </inertial>

  <!-- make the sphere invisible -->
  <visual>
    <origin xyz="0 0 0" />
    <geometry>
      <sphere radius="${(radius-width/2)*0.999}" />
    </geometry>
  </visual>

  <collision>
    <origin xyz="0 0 0" />
    <geometry>
      <sphere radius="${(radius-width/2)*0.999}" />
    </geometry>
  </collision>
</link>

<gazebo reference="front_sphere">
  <mu1>0.0</mu1>
  <mu2>0.0</mu2>
</gazebo>

<joint name="front_support" type="fixed">
  <parent link="body_link" />
  <child link="front_sphere" />
  <origin xyz="${width/2-(radius-width/2)*0.99} 0 0" rpy="0 0 0" />
</joint>


<!-- back sphere support -->
<link name="back_sphere">
  <inertial>
    <mass value="0.0000001" />
    <origin xyz="0 0 0" />
    <inertia ixx="0.00000000001" ixy="0.0" ixz="0.0"
      iyy="0.00000000001" iyz="0.0"
      izz="0.00000000001" />
  </inertial>

  <visual>
    <origin xyz="0 0 0" />
    <geometry>
      <sphere radius="${(radius-width/2)*0.99}" />
    </geometry>
  </visual>

  <collision>
    <origin xyz="0 0 0" />
    <geometry>
      <sphere radius="${(radius-width/2)*0.99}" />
    </geometry>
  </collision>
</link>

<gazebo reference="back_sphere">
  <mu1>0.0</mu1>
  <mu2>0.0</mu2>
</gazebo>

<joint name="back_support" type="fixed">
  <parent link="body_link" />
  <child link="back_sphere" />
  <origin xyz="${-width/2+(radius-width/2)*0.99} 0 0" rpy="0 0 0" />
</joint>


<link name="left_wheel">
  <inertial>
    <mass value="${mass2}" />
    <origin xyz="0 0 ${length/2}" />
    <inertia ixx="${mass2/12*(3*radius*radius+length*length)}" ixy="0.0" ixz="0.0"
      iyy="${mass2/12*(3*radius*radius+length*length)}" iyz="0.0"
      izz="${mass2/2*radius*radius}" />
  </inertial>

  <!-- use regular cylinder if wanting smooth visual experience -->
  <!-- remember to set color to grey in gazebo tag -->
  <!-- or low definition wheel if wanting to observe wheel rotation -->
  <visual>
    <origin xyz="0 0 ${length/2}" />
    <geometry>
      <cylinder radius="${radius}" length="${length}" />
      <!-- <mesh filename="package://two_wheel_robot_description/urdf/mesh/twowheel_left_hd.dae"/> -->
      <!-- <mesh filename="package://two_wheel_robot_description/urdf/mesh/twowheel_left_ld.dae"/> -->
    </geometry>
  </visual>

  <!-- collision can always be simple as a cylinder -->
  <collision>
    <origin xyz="0 0 ${length/2}" />
    <geometry>
      <cylinder radius="${radius}" length="${length}" />
      <!-- <mesh filename="package://two_wheel_robot_description/urdf/mesh/twowheel_left_hd.dae"/> -->
      <!-- <mesh filename="package://two_wheel_robot_description/urdf/mesh/twowheel_left_ld.dae"/> -->
    </geometry>
  </collision>
</link>

<gazebo reference="left_wheel">
  <!-- <material>Gazebo/Grey</material> -->
  <material>Gazebo/Blue</material>
  <mu1>1</mu1>
  <mu2>0.5</mu2>
</gazebo>


<!-- <link name="left_wheel_mark">
  <inertial>
    <mass value="0.0000001" />
    <origin xyz="0 0 0" />
    <inertia ixx="0.00000000001" ixy="0.0" ixz="0.0"
      iyy="0.00000000001" iyz="0.0"
      izz="0.00000000001" />
  </inertial>

  <visual>
    <origin xyz="0 0 0" />
    <geometry>
      <mesh filename="package://two_wheel_robot_description/urdf/mesh/twowheel_left_mark.dae"/>
    </geometry>
  </visual>

  <collision>
    <origin xyz="0 0 0" />
    <geometry>
      <mesh filename="package://two_wheel_robot_description/urdf/mesh/twowheel_left_mark.dae"/>
    </geometry>
  </collision>
</link>

<joint name="left_wheel_mark_fixed" type="continuous">
  <parent link="left_wheel" />
  <child link="left_wheel_mark" />
  <origin xyz="0 0 0.014" rpy="0 0 0" />
  <axis xyz="0 0 1" />
</joint> -->


<link name="right_wheel">
    <inertial>
    <mass value="${mass2}" />
    <origin xyz="0 0 ${length/2}" />
    <inertia ixx="${mass2/12*(3*radius*radius+length*length)}" ixy="0.0" ixz="0.0"
      iyy="${mass2/12*(3*radius*radius+length*length)}" iyz="0.0"
      izz="${mass2/2*radius*radius}" />
  </inertial>

  <!-- use regular cylinder if wanting smooth visual experience -->
  <!-- remember to set color to grey in gazebo tag -->
  <!-- or low definition wheel if wanting to observe wheel rotation -->
  <visual>
    <origin xyz="0 0 ${length/2}" />
    <geometry>
      <cylinder radius="${radius}" length="${length}" />
      <!-- <mesh filename="package://two_wheel_robot_description/urdf/mesh/twowheel_left_hd.dae"/> -->
      <!-- <mesh filename="package://two_wheel_robot_description/urdf/mesh/twowheel_left_ld.dae"/> -->
    </geometry>
  </visual>

  <!-- collision can always be simple as a cylinder -->
  <collision>
    <origin xyz="0 0 ${length/2}" />
    <geometry>
      <cylinder radius="${radius}" length="${length}" />
      <!-- <mesh filename="package://two_wheel_robot_description/urdf/mesh/twowheel_left_hd.dae"/> -->
      <!-- <mesh filename="package://two_wheel_robot_description/urdf/mesh/twowheel_left_ld.dae"/> -->
    </geometry>
  </collision>
</link>

<gazebo reference="right_wheel">
  <!-- <material>Gazebo/Grey</material> -->
  <material>Gazebo/Red</material>
  <mu1>1</mu1>
  <mu2>0.5</mu2>
</gazebo>

<joint name="base_joint" type="fixed">
  <parent link="base_link"/>
  <child link="body_link"/>
</joint>


<joint name="left_motor" type="continuous">
  <parent link="body_link" />
  <child link="left_wheel" />
  <origin xyz="0 ${width/2+0.001} ${width/2}" rpy="-1.5708 0 0" />
  <axis xyz="0 0 1" />
</joint>


<joint name="right_motor" type="continuous">
  <parent link="body_link" />
  <child link="right_wheel" />
  <!-- <origin xyz="0 0.0177 0.0127" rpy="1.5708 0 0" /> -->
  <origin xyz="0 ${-width/2-0.001} ${width/2}" rpy="1.5708 0 0" />
  <axis xyz="0 0 -1" />
<!--   axis setting, invert the direction
  so that two wheels are tuned at the same direction, which means
  when the same wheel position command is given, both wheels will make the same effect
  of pushing the robot forward or backward -->
</joint>

<!--   Sensor link  -->
  <link name="sensor_laser">
    <inertial>
      <origin xyz="0 0 ${length3/2}" rpy="0 0 0" />
      <mass value="${mass3}" />
  
       <inertia ixx="${mass3/12*(3*radius3*radius3+length3*length3)}" ixy="0.0" ixz="0.0"
      iyy="${mass3/12*(3*radius3*radius+length3*length3)}" iyz="0.0"
      izz="${mass3/2*radius3*radius3}" />
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${radius3}" length="${length3}" />
      </geometry>
      <material name="orange" />
    </visual>

    <collision>
      <origin xyz="0 0 ${length3/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${radius3}" length="${length3}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="sensor_laser">
    <!-- <material>Gazebo/Grey</material> -->
    <material>Gazebo/Orange</material>
    <mu1>1</mu1>
    <mu2>0.5</mu2>
  </gazebo>
  <joint name="joint_sensor_laser" type="fixed">
    <origin xyz="0 0 ${width/2}" rpy="0 0 0"/>
    <parent link="body_link"/>
    <child link="sensor_laser"/>
  </joint> 

</robot>